### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by Two-Tone** [ProjectJoyeuse/PathsOfJjaro#4]
There is no LICENSE file specified, because of that, even though the code is viewable, the project is ***NOT*** open source at the moment.  The license and what rights it gives the users is what makes something open source, not that you can view the code.

Personally I suggest going with GPL for the code because of what happened with DOOM 1.  DOOM 1's source code was not originally released as GPL and as a result to this day there are still Doom communities that don't open the code since the original license didn't require it. Those forks will eventually die when the maintainers disappear and no one will be able to do anything except *maybe* provide lifesupport via emulation or something.

For a project like this GPL makes the most sense to me. You ensure all future forks and contributions are open source, you can still use any open source library you want, and it's *very* pro-consumer.

---

For art assets I suggest a Creative Commons license.  You guys can figure out which form of CC you want to use with this super simple tool. https://creativecommons.org/choose/

**Comment by yaelatletl** [comment]
Marathon has been ambiguous for its licenses, as we don't actually use any code from the original game, the code is under the MIT license, but the assets are CC-BY-SA-NC. Licenses are scattered but I'll gather them in the repo

**Comment by yaelatletl** [comment]
Licenses added in d70157f , if you still have doubts about the choice of the MIT Licence, check the other repos of the organization, there may be room to closed source forks to improve the engine or the framework, but as long as the main Godot community stays active upgrades will come to everyone
